update check-white-space.yml

diff --git a/.github/workflows/check-white-space.yml b/.github/workflows/check-white-space.yml
--- a/.github/workflows/check-white-space.yml
+++ b/.github/workflows/check-white-space.yml
@@ -1,4 +1,4 @@
-name: Check Trailing Whitespace
+name: Check Whitespace and New Line
 
 on:
   push:
@@ -11,6 +11,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v1
-    - name: Check space
+    - name: Check trailing space
       run: if grep -rIn "[[:blank:]]$"; then exit 2; else echo OK; fi
+    - name: Check no new line at EOF
+      run: fail=1; for f in $(grep -rIl ""); do if test $(tail -c 1 $f); then echo $f; fail=0; fi; done; if $fail; then exit 1; fi
 
